aml: Add gatekeeper to manifest.xml
Fixes build error:

Both device manifest and kernel release do not specify kernel FCM version.
getKernelLevel:
ERROR: files are incompatible: Device manifest and framework compatibility
matrix are incompatible: HALs incompatible. Matrix level = 4.
Manifest level = 4. The following requirements are not met:
android.hardware.gatekeeper:
    required: @1.0::IGatekeeper/default
    provided:
: Success

Change-Id: I9a69dfdc1d18c6362fb365cfcbd019b574784300